export const ALL_PRODUCTS_GET_REQUEST = "ALL_PRODUCTS_GET_REQUEST";
export const ALL_PRODUCTS_GET_SUCCESS = "ALL_PRODUCTS_GET_SUCCESS";
export const ALL_PRODUCTS_GET_FAIL = "ALL_PRODUCTS_GET_FAIL";

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
