export const UESR_REGISTER_REQUEST = "UESR_REGISTER_REQUEST";
export const UESR_REGISTER_SUCCESS = "UESR_REGISTER_SUCCESS";
export const UESR_REGISTER_FAIL = "UESR_REGISTER_FAIL";

export const UESR_LOGIN_REQUEST = "UESR_LOGIN_REQUEST";
export const UESR_LOGIN_SUCCESS = "UESR_LOGIN_SUCCESS";
export const UESR_LOGIN_FAIL = "UESR_LOGIN_FAIL";

export const UESR_LOAD_REQUEST = "UESR_LOAD_REQUEST";
export const UESR_LOAD_SUCCESS = "UESR_LOAD_SUCCESS";
export const UESR_LOAD_FAIL = "UESR_LOAD_FAIL";

export const USER_LOGOUT_SUCCESS = "UESR_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "UESR_LOGOUT_FAIL";
